FROM buildpack-deps:jessie

# frontend environment init
ENV NODE_VERSION 13.6.0
ENV NPM_VERSION 6.13.6

RUN curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
    && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
    && rm "node-v$NODE_VERSION-linux-x64.tar.gz" \
    && npm install -g npm@"$NPM_VERSION" --registry https://registry.npm.taobao.org \
    && apt-get update \
    && apt-get install vim -y
